/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mentor;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;

/**
 *
 * @author guilhermetravaglialargura
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    
    ArrayList<Aluno> arrayAluno = new ArrayList();
    ArrayList<Professor> arrayProfessor = new ArrayList();
    ListagemAluno Taluno = new ListagemAluno();
    ListagemProfessor Tprofessor = new ListagemProfessor();
    
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lnome = new javax.swing.JLabel();
        Lcpf = new javax.swing.JLabel();
        Ltelefone = new javax.swing.JLabel();
        LdataAdmissao = new javax.swing.JLabel();
        LsalarioBruto = new javax.swing.JLabel();
        Lmatricula = new javax.swing.JLabel();
        Tcidade = new javax.swing.JTextField();
        Tcpf = new javax.swing.JTextField();
        Ttelefone = new javax.swing.JTextField();
        TdataAdmissao = new javax.swing.JTextField();
        TsalarioBruto = new javax.swing.JTextField();
        Tmatricula = new javax.swing.JTextField();
        Bcadastrar = new javax.swing.JButton();
        CB1 = new javax.swing.JComboBox<>();
        Bvoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tnome1 = new javax.swing.JTextField();
        Trua = new javax.swing.JTextField();
        Tbairro = new javax.swing.JTextField();
        Testado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lnome.setText("Nome:");

        Lcpf.setText("CPF:");

        Ltelefone.setText("Telefone:");

        LdataAdmissao.setText("Data Admissao:");
        LdataAdmissao.setEnabled(false);

        LsalarioBruto.setText("Salario Bruto:");
        LsalarioBruto.setEnabled(false);

        Lmatricula.setText("Matricula:");
        Lmatricula.setEnabled(false);

        Tcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcpfActionPerformed(evt);
            }
        });

        TdataAdmissao.setEnabled(false);
        TdataAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdataAdmissaoActionPerformed(evt);
            }
        });

        TsalarioBruto.setEnabled(false);

        Tmatricula.setEnabled(false);
        Tmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TmatriculaActionPerformed(evt);
            }
        });

        Bcadastrar.setText("Cadastrar");
        Bcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcadastrarActionPerformed(evt);
            }
        });

        CB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção *", "Professor", "Aluno" }));
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });

        Bvoltar.setText("< voltar");
        Bvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Rua:");

        jLabel2.setText("Bairro:");

        jLabel3.setText("Cidade:");

        jLabel4.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ttelefone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lnome)
                                    .addComponent(Lcpf)
                                    .addComponent(LdataAdmissao))
                                .addGap(0, 45, Short.MAX_VALUE))
                            .addComponent(Tnome1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tcpf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TdataAdmissao))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(Tcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Testado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Trua, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bvoltar)
                        .addGap(50, 50, 50)
                        .addComponent(CB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lmatricula)
                            .addComponent(Ltelefone))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Tmatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(LsalarioBruto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TsalarioBruto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnome)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tnome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Trua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcpf)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ltelefone)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LdataAdmissao)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TdataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Testado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Lmatricula)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bcadastrar)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Tmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LsalarioBruto)
                        .addGap(1, 1, 1)
                        .addComponent(TsalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcpfActionPerformed

    private void TmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TmatriculaActionPerformed

    private void BvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvoltarActionPerformed
        // TODO add your handling code here:
        Menu telaMenu = new Menu();
        telaMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BvoltarActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        // TODO add your handling code here:
        if (CB1.getSelectedIndex() == 1){
            TdataAdmissao.setEnabled(true);
            TsalarioBruto.setEnabled(true);
            LdataAdmissao.setEnabled(true);
            LsalarioBruto.setEnabled(true);
            LdataAdmissao.setText("Data Admissao:");
            LsalarioBruto.setText("Salario Bruto:");
        }else if (CB1.getSelectedIndex() == 2){
            TdataAdmissao.setEnabled(true);
            TsalarioBruto.setEnabled(true);
            LdataAdmissao.setEnabled(true);
            LsalarioBruto.setEnabled(true);
            Tmatricula.setEnabled(true);
            Lmatricula.setEnabled(true);
            LdataAdmissao.setText("Data Nascimento:");
            LsalarioBruto.setText("Periodo:");
        } else {
            TdataAdmissao.setEnabled(false);
            TsalarioBruto.setEnabled(false);
            LdataAdmissao.setEnabled(false);
            LsalarioBruto.setEnabled(false);
            Tmatricula.setEnabled(false);
            Lmatricula.setEnabled(false);
        }
    }//GEN-LAST:event_CB1ActionPerformed

    private void BcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcadastrarActionPerformed
        // TODO add your handling code here:
        ConexoesMySQL sql = new ConexoesMySQL();
        Connection conn = sql.realizaConexaoMySQL();
        if (CB1.getSelectedIndex() == 1){
            Professor novoProfessor = new Professor();
            novoProfessor.setNome(Tcidade.getText());
            novoProfessor.setCpf(Long.parseLong(Tcpf.getText()));
            novoProfessor.setTelefone(Ttelefone.getText());
            novoProfessor.setDataAdmissao(TdataAdmissao.getText());
            novoProfessor.setSalarioBruto(Double.parseDouble(TsalarioBruto.getText()));
            novoProfessor.setRua(Trua.getText());
            novoProfessor.setBairro(Tbairro.getText());
            novoProfessor.setCidade(Tcidade.getText());
            novoProfessor.setEstado(Testado.getText());
            arrayProfessor.add(novoProfessor);
            this.Tprofessor = Tprofessor;
            DefaultTableModel model = (DefaultTableModel) this.Taluno.JTaluno.getModel();
            for (Professor obj: arrayProfessor){
                model.addRow(new Object[] {obj.getNome(), obj.getCpf(), obj.getTelefone(), obj.getDataAdmissao(), obj.getSalarioBruto()});
                // sql.insereDadosNoMySQL(obj.getNome(), obj.getCpf(), obj.getTelefone(), obj.getDataAdmissao(), NORMAL, ERROR);
            }
        } else if (CB1.getSelectedIndex() == 2){
            Aluno novoAluno = new Aluno();
            novoAluno.setNome(Tcidade.getText());
            novoAluno.setCpf(Long.parseLong(Tcpf.getText()));
            novoAluno.setTelefone(Ttelefone.getText());
            novoAluno.setMatricula(Long.parseLong(Tmatricula.getText()));
            novoAluno.setDataNascimento(TdataAdmissao.getText());
            novoAluno.setPeriodo(Integer.parseInt(TsalarioBruto.getText()));
            novoAluno.setRua(Trua.getText());
            novoAluno.setBairro(Tbairro.getText());
            novoAluno.setCidade(Tcidade.getText());
            novoAluno.setEstado(Testado.getText());
            arrayAluno.add(novoAluno);
            this.Taluno = Taluno;
            DefaultTableModel model = (DefaultTableModel) this.Taluno.JTaluno.getModel();
            for (Aluno obj: arrayAluno){
                model.addRow(new Object[] {obj.getNome(), obj.getCpf(), obj.getDataNascimento(), obj.getTelefone(), obj.getMatricula(), obj.getPeriodo(), obj.getRua(), obj.getBairro(), obj.getCidade(), obj.getEstado()});
                sql.insereDadosNoMySQL(obj.getNome(), obj.getCpf(), obj.getTelefone(), obj.getDataNascimento(), obj.getMatricula(), obj.getPeriodo(), obj.getRua(), obj.getBairro(), obj.getCidade(), obj.getEstado());
            }
        }
        sql.desconectaMySQL(conn);
    }//GEN-LAST:event_BcadastrarActionPerformed

    private void TdataAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdataAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdataAdmissaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcadastrar;
    private javax.swing.JButton Bvoltar;
    private javax.swing.JComboBox<String> CB1;
    private javax.swing.JLabel Lcpf;
    private javax.swing.JLabel LdataAdmissao;
    private javax.swing.JLabel Lmatricula;
    private javax.swing.JLabel Lnome;
    private javax.swing.JLabel LsalarioBruto;
    private javax.swing.JLabel Ltelefone;
    private javax.swing.JTextField Tbairro;
    private javax.swing.JTextField Tcidade;
    private javax.swing.JTextField Tcpf;
    private javax.swing.JTextField TdataAdmissao;
    private javax.swing.JTextField Testado;
    private javax.swing.JTextField Tmatricula;
    private javax.swing.JTextField Tnome1;
    private javax.swing.JTextField Trua;
    private javax.swing.JTextField TsalarioBruto;
    private javax.swing.JTextField Ttelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
